export const MESSAGES = {
  RECORD_ADDED_SUCCESSFULLY: 'Record added successfully.',
  RECORD_FETCHED_SUCCESSFULLY: 'Record fetched successfully.',
  RECORD_DELETED_SUCCESSFULLY: 'Record deleted successfully.',
  RECORD_UPDATED_SUCCESSFULLY: 'Record updated successfully.',
  NO_RECORD: 'No record found.',
  LOGIN: 'Login successfully.',
  UNAUTHORIZED: 'Unauthorized resources.',
  INTERNAL_SERVER_ERROR: 'Internal server error.',
  USER_EMAIL_EXISTS: 'User with this email already exists',
  EMPTY_RECORD: 'Record to be update must not be empty.',
  IS_REQUIRED: ' is required',
  ONLY_ALPHABETIC: ' must contain only alphabetic characters',
  ONLY_ALPHANUMERIC: ' must contain only alphabetic and number characters',
  EMAIL_FORMAT_INVALID: 'Email format is invalid',
  PASSWORD_COMPLEXITY: 'Password must be at least 8 characters long, with at least one lowercase letter, one uppercase letter, one numeric digit, and one special character',
  INCORRECT: 'Incorrect email or password.',
  FORBIDDEN: 'Forbidden resources.',
  SIGNUP_SUCCESSFULLY: 'Account created successfully.',
  MARKS_RANGE: 'Marks must be 0 to 100.',
  INVALID_GRADE: 'Grade valuse must lies in A+, A-, B+, B- and F.',
  INVALID_ENTRY: ' has invalid entry.',
  ACCOUNT_NOT_EXISIT: 'Account does not exist.',
};
